This is makeindex, version 2.15 [TeX Live 2011] (kpathsea + Thai support).
Scanning style file ./rapport.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file rapport.acn....done (118 entries accepted, 0 rejected).
Sorting entries....done (962 comparisons).
Generating output file rapport.acr....done (81 lines written, 0 warnings).
Output written in rapport.acr.
Transcript written in rapport.alg.
